version: '3'

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik-demo-1
    # command: --api.insecure=true --providers.docker
    ports:
      - "82:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yaml:ro
    restart: unless-stopped
    networks:
      - frontend
networks:
  frontend:
    external: true