global:
  checkNewVersion: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entrypoint:
  web:
    address: 80
  websecure:
    address: 443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
networks:
  frontend:
    external: true